### ISSUE TITLE
Quick Fix: Typo "repositories" 

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/git-version-control-pushing-code-with-git#2]
Lesson very well-written. Thank you. 
Line 5 typo  "repositories" 
************
Introduction
You may have heard of GitHub before. In the previous lesson, you used it to get Facebook's code for the React framework. For all the amazing power that GitHub provides (Microsoft thought it was so powerful that they bought GitHub for a cool $7.5 billion), as far as Git is concerned they're just a big old server that hosts a whole bunch of remote respositories ("remotes").

**Comment by Sdcrouse** [comment]
I just submitted a pull request to them here: [https://github.com/learn-co-students/git-version-control-pushing-code-with-git-v-000/pull/4](https://github.com/learn-co-students/git-version-control-pushing-code-with-git-v-000/pull/4)

---Sdcrouse

**Comment by drakeltheryuujin** [comment]
Hi @ccklight,

We've updated the materials and believe the typo has been fixed.
Thanks for your feedback!
